package com.queryhub.notification.entity;

import com.queryhub.common.events.EventType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Notification entity persisted in notification_db.
 * Each row represents one activity notification generated from a Kafka event.
 */
@Entity
@Table(name = "notifications")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Notification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** ID of the query this notification relates to. */
    @Column(name = "query_id", nullable = false)
    private Long queryId;

    /** Category name of the query (consistent with event categoryName). */
    @Column(name = "category_name", length = 100)
    private String categoryName;

    /** Strongly-typed event type stored as string. */
    @Enumerated(EnumType.STRING)
    @Column(name = "event_type", nullable = false, length = 50)
    private EventType eventType;

    /** Username of the user who triggered the action. */
    @Column(name = "actor_username", nullable = false, length = 100)
    private String actorUsername;

    /** Human-readable notification message generated by NotificationMapper. */
    @Column(name = "message", nullable = false, length = 500)
    private String message;

    /** Timestamp when this notification was persisted. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
